server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        # Not needed since we excluded the dependency, but
        # still good to add it here for better readability
        enabled: false
      consul:
        enabled: true
        discovery:
          # Get only services that are passing the health check
          query-passing: true
    gateway:
      routes:
        - id: multiplication
#          uri: http://localhost:8080/
          uri: lb://multiplication/
          predicates:
            - Path=/challenges/**,/attempts,/attempts/**,/users/**
        - id: gamification
#          uri: http://localhost:8081/
          uri: lb://gamification/
          predicates:
            - Path=/leaders
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
        default-filters:
          - name: Retry
            args:
              retries: 3
              methods: GET,POST
      # Uncomment the configuration below if you want to enable route matching logs
      #logging:
      #  level:
      #    org.springframework.cloud.gateway.handler.predicate: trace
